
version: '3.8'

services:
  mongo1:
    build: .
    container_name: mongo1
    hostname: mongo1
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo1:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  mongo2:
    image: mongo:4.4
    container_name: mongo2
    hostname: mongo2
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ./data/mongo2:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  mongo3:
    image: mongo:4.4
    container_name: mongo3
    hostname: mongo3
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - ./data/mongo3:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

networks:
  default:
    name: mongo-net


