
name: MongoDB Replica CI/CD

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: mongo-replica
  DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/mongo-replica

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t $DOCKER_REPO:latest .

    - name: Push Docker image
      run: docker push $DOCKER_REPO:latest


